# SwiftLint configuration for swift-mlx-server

# Rule Configuration
disabled_rules:
  - trailing_whitespace
  - line_length # MLX operations can have longer parameter lists
  - file_length # Some route files are necessarily long
  - type_body_length # Model providers can be large
  - function_body_length # Generation functions can be complex
  
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

analyzer_rules:
  - unused_import
  - unused_declaration

# Rule Parameters
line_length:
  warning: 140
  error: 200
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

type_body_length:
  warning: 400
  error: 600

file_length:
  warning: 600
  error: 1000
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 10
  error: 18

type_name:
  min_length: 3
  max_length:
    warning: 50
    error: 60

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  allowed_symbols: ["_"]
  excluded:
    - id
    - ok
    - no
    - n
    - i
    - B
    - S

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 3
    error: 5

large_tuple:
  warning: 3
  error: 4

# Excluded paths
excluded:
  - .build
  - DerivedData
  - Package.swift
  - Tests
  - docs
  - scripts
  - dist
  - temp
  - build
  - .swiftpm

# Custom Rules
custom_rules:
  avoid_print:
    name: "Avoid print()"
    regex: '\bprint\('
    message: "Use Logger instead of print() for production code"
    severity: warning
    
  force_unwrapping:
    name: "Force Unwrapping"
    regex: '(?<![\.!])\b\w+!\s*(?![=!<>])'
    message: "Avoid force unwrapping. Use if let or guard let instead."
    severity: warning
    
  force_cast:
    name: "Force Cast"
    regex: '\sas!\s'
    message: "Avoid force casting. Use conditional casting instead."
    severity: error
    
    
  todo_fixme:
    name: "TODO/FIXME"
    regex: '(TODO|FIXME|HACK|XXX):'
    message: "TODO/FIXME should be addressed before production"
    severity: warning

# Reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, markdown, github-actions-logging)
reporter: "xcode"